table players-data-updated
	lineageTag: 1f3b65e4-fd45-4029-9567-304490ccf33f

	column player_id
		dataType: int64
		formatString: 0
		lineageTag: 18f0bc8b-885c-447a-99e5-88a9d6a5b810
		summarizeBy: sum
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column player_name
		dataType: string
		lineageTag: b62fa301-7a46-4682-b4e0-bb545239f7b5
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = Automatic

	column bat_style
		dataType: string
		lineageTag: d76a30d8-8cc3-42c3-b57f-6ea65448df46
		summarizeBy: none
		sourceColumn: bat_style

		annotation SummarizationSetBy = Automatic

	column bowl_style
		dataType: string
		lineageTag: bd12d946-bc59-4e2a-93fd-33ba778c5eaf
		summarizeBy: none
		sourceColumn: bowl_style

		annotation SummarizationSetBy = Automatic

	column field_pos
		dataType: string
		lineageTag: e2f97931-92b7-4c85-a4e5-2074eb8ec568
		summarizeBy: none
		sourceColumn: field_pos

		annotation SummarizationSetBy = Automatic

	column player_full_name
		dataType: string
		lineageTag: ae9471dc-61be-47a5-9dcd-f4c9df45f18a
		summarizeBy: none
		sourceColumn: player_full_name

		annotation SummarizationSetBy = Automatic

	column player_name2
		dataType: string
		lineageTag: 1c84d73c-16d9-4569-b15e-96a8d04ab51c
		summarizeBy: none
		sourceColumn: player_name2

		annotation SummarizationSetBy = Automatic

	column player_image
		dataType: string
		lineageTag: 3b83edc1-c307-4c4f-8e60-f4004131662c
		summarizeBy: none
		sourceColumn: player_image

		annotation SummarizationSetBy = Automatic

	partition players-data-updated = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KAZI-PC\Downloads\IPL Analysis 2008 - 2025 Data-20250722T093633Z-1-001\IPL Analysis 2008 - 2025 Data\IPL Data\players-data-updated.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"player_id", Int64.Type}, {"player_name", type text}, {"bat_style", type text}, {"bowl_style", type text}, {"field_pos", type text}, {"player_full_name", type text}, {"player_name2", type text}, {"player_image", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

