table ball_by_ball_data
	lineageTag: 2a703970-e832-4bd9-b3e5-d2e578bfd9d6

	column season_id
		dataType: int64
		formatString: 0
		lineageTag: 77cbc41e-3fb8-4084-b550-8813d22189ff
		summarizeBy: sum
		sourceColumn: season_id

		annotation SummarizationSetBy = Automatic

	column match_id
		dataType: int64
		formatString: 0
		lineageTag: 010c393b-6aab-4ee5-bf65-fa672050ab5b
		summarizeBy: none
		sourceColumn: match_id

		annotation SummarizationSetBy = Automatic

	column batter
		dataType: string
		lineageTag: 9ca02d78-eef3-4d1c-a628-a0c285c60d16
		summarizeBy: none
		sourceColumn: batter

		annotation SummarizationSetBy = Automatic

	column bowler
		dataType: string
		lineageTag: 2df55ae4-9168-4caa-923b-62bad380ef31
		summarizeBy: none
		sourceColumn: bowler

		annotation SummarizationSetBy = Automatic

	column non_striker
		dataType: string
		lineageTag: b0a894a6-f1c3-43c9-8712-61768f1cf578
		summarizeBy: none
		sourceColumn: non_striker

		annotation SummarizationSetBy = Automatic

	column team_batting
		dataType: string
		lineageTag: a22f91bb-9074-4de8-9e77-1a8c64a3b9ae
		summarizeBy: none
		sourceColumn: team_batting

		annotation SummarizationSetBy = Automatic

	column team_bowling
		dataType: string
		lineageTag: 7e5e5c2c-8e06-4720-ae8c-0d74148ab432
		summarizeBy: none
		sourceColumn: team_bowling

		annotation SummarizationSetBy = Automatic

	column over_number
		dataType: int64
		formatString: 0
		lineageTag: f9ea2ff1-66b2-430e-9ae3-f84f58c49e86
		summarizeBy: sum
		sourceColumn: over_number

		annotation SummarizationSetBy = Automatic

	column ball_number
		dataType: int64
		formatString: 0
		lineageTag: a9f70e90-8cb6-4768-833d-d5062e5e90c7
		summarizeBy: sum
		sourceColumn: ball_number

		annotation SummarizationSetBy = Automatic

	column batter_runs
		dataType: int64
		formatString: 0
		lineageTag: ecfd75ad-0f93-41cb-a0ee-67734aa3004f
		summarizeBy: sum
		sourceColumn: batter_runs

		annotation SummarizationSetBy = Automatic

	column extras
		dataType: int64
		formatString: 0
		lineageTag: 22df1178-59a6-4172-a250-962ea45fe748
		summarizeBy: sum
		sourceColumn: extras

		annotation SummarizationSetBy = Automatic

	column total_runs
		dataType: int64
		formatString: 0
		lineageTag: 39eb70d2-8094-4846-a908-df14cc76e7eb
		summarizeBy: sum
		sourceColumn: total_runs

		annotation SummarizationSetBy = Automatic

	column batsman_type
		dataType: string
		lineageTag: 9b925a5b-d461-469e-b83a-3f82507747d0
		summarizeBy: none
		sourceColumn: batsman_type

		annotation SummarizationSetBy = Automatic

	column bowler_type
		dataType: string
		lineageTag: 4fef3e98-e610-4600-be9a-554ac201f9f4
		summarizeBy: none
		sourceColumn: bowler_type

		annotation SummarizationSetBy = Automatic

	column player_out
		dataType: string
		lineageTag: f3302846-2405-48c1-8b1b-076ad851cd63
		summarizeBy: none
		sourceColumn: player_out

		annotation SummarizationSetBy = Automatic

	column fielders_involved
		dataType: string
		lineageTag: 107c895e-5cb8-48da-80d0-e0269daccdfa
		summarizeBy: none
		sourceColumn: fielders_involved

		annotation SummarizationSetBy = Automatic

	column is_wicket
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ee669c04-fc67-4da7-8160-51ec613351ef
		summarizeBy: none
		sourceColumn: is_wicket

		annotation SummarizationSetBy = Automatic

	column is_wide_ball
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5e94ad5e-e074-4b11-aa50-a119b4c866f9
		summarizeBy: none
		sourceColumn: is_wide_ball

		annotation SummarizationSetBy = Automatic

	column is_no_ball
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 203e2677-3393-4742-8faf-0f3cd8e0de8c
		summarizeBy: none
		sourceColumn: is_no_ball

		annotation SummarizationSetBy = Automatic

	column is_leg_bye
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 44f9e6b5-660f-49a0-8a80-c2c176fb0881
		summarizeBy: none
		sourceColumn: is_leg_bye

		annotation SummarizationSetBy = Automatic

	column is_bye
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ce242ea9-8f9a-47b5-ac2e-cb0ce03115c1
		summarizeBy: none
		sourceColumn: is_bye

		annotation SummarizationSetBy = Automatic

	column is_penalty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7001495a-5f8f-4475-9e35-8788f23988e4
		summarizeBy: none
		sourceColumn: is_penalty

		annotation SummarizationSetBy = Automatic

	column wide_ball_runs
		dataType: int64
		formatString: 0
		lineageTag: 36232416-c2a3-464c-b581-5eed2d3cd953
		summarizeBy: sum
		sourceColumn: wide_ball_runs

		annotation SummarizationSetBy = Automatic

	column no_ball_runs
		dataType: int64
		formatString: 0
		lineageTag: e96a1435-de84-4fe0-aecc-cbdb976a3343
		summarizeBy: sum
		sourceColumn: no_ball_runs

		annotation SummarizationSetBy = Automatic

	column leg_bye_runs
		dataType: int64
		formatString: 0
		lineageTag: 9cdc9881-3760-44f2-95b0-dde8b96af044
		summarizeBy: sum
		sourceColumn: leg_bye_runs

		annotation SummarizationSetBy = Automatic

	column bye_runs
		dataType: int64
		formatString: 0
		lineageTag: ba71058f-7647-43c3-b993-6569e4ab9db8
		summarizeBy: sum
		sourceColumn: bye_runs

		annotation SummarizationSetBy = Automatic

	column penalty_runs
		dataType: int64
		formatString: 0
		lineageTag: c514f7af-10e9-418b-b51a-274101b996ad
		summarizeBy: sum
		sourceColumn: penalty_runs

		annotation SummarizationSetBy = Automatic

	column wicket_kind
		dataType: string
		lineageTag: 3186a546-8d9f-46ff-94c4-b156c4eb406d
		summarizeBy: none
		sourceColumn: wicket_kind

		annotation SummarizationSetBy = Automatic

	column is_super_over
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 91605e27-f30d-4386-ae4a-ff2b421fd79f
		summarizeBy: none
		sourceColumn: is_super_over

		annotation SummarizationSetBy = Automatic

	column innings
		dataType: int64
		formatString: 0
		lineageTag: 3c2de349-8e2c-4894-9453-305f1031e629
		summarizeBy: sum
		sourceColumn: innings

		annotation SummarizationSetBy = Automatic

	partition ball_by_ball_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KAZI-PC\Downloads\IPL Analysis 2008 - 2025 Data-20250722T093633Z-1-001\IPL Analysis 2008 - 2025 Data\IPL Data\ball_by_ball_data.csv"),[Delimiter=",", Columns=30, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"season_id", Int64.Type}, {"match_id", Int64.Type}, {"batter", type text}, {"bowler", type text}, {"non_striker", type text}, {"team_batting", type text}, {"team_bowling", type text}, {"over_number", Int64.Type}, {"ball_number", Int64.Type}, {"batter_runs", Int64.Type}, {"extras", Int64.Type}, {"total_runs", Int64.Type}, {"batsman_type", type text}, {"bowler_type", type text}, {"player_out", type text}, {"fielders_involved", type text}, {"is_wicket", type logical}, {"is_wide_ball", type logical}, {"is_no_ball", type logical}, {"is_leg_bye", type logical}, {"is_bye", type logical}, {"is_penalty", type logical}, {"wide_ball_runs", Int64.Type}, {"no_ball_runs", Int64.Type}, {"leg_bye_runs", Int64.Type}, {"bye_runs", Int64.Type}, {"penalty_runs", Int64.Type}, {"wicket_kind", type text}, {"is_super_over", type logical}, {"innings", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

