table teams_data
	lineageTag: 84053ab4-1de1-4ba4-9d9a-4cdbad631f8a

	column team_id
		dataType: int64
		formatString: 0
		lineageTag: 1e387a9b-3300-4cec-96a2-2b848de245cd
		summarizeBy: none
		sourceColumn: team_id

		annotation SummarizationSetBy = Automatic

	column team_name
		dataType: string
		lineageTag: 352197ed-50fd-4cd2-ad7a-87af8d988852
		summarizeBy: none
		sourceColumn: team_name

		annotation SummarizationSetBy = Automatic

	column team_name_short
		dataType: string
		lineageTag: 2ddc27e5-3f24-4709-a523-296e3fea46dd
		summarizeBy: none
		sourceColumn: team_name_short

		annotation SummarizationSetBy = Automatic

	column image_url
		dataType: string
		lineageTag: b561d5ef-4eed-4b9f-8bc5-b0b8b8466b4b
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: image_url

		annotation SummarizationSetBy = Automatic

	partition teams_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KAZI-PC\Downloads\IPL Analysis 2008 - 2025 Data-20250722T093633Z-1-001\IPL Analysis 2008 - 2025 Data\IPL Data\teams_data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team_id", Int64.Type}, {"team_name", type text}, {"team_name_short", type text}, {"image_url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

